export const ESCROW_ABI = [
  // ── Write ──
  {
    type: "function",
    name: "listNFT",
    inputs: [
      { name: "nftContract", type: "address" },
      { name: "tokenId", type: "uint256" },
      { name: "amount", type: "uint256" },
      { name: "apr", type: "uint256" },
      { name: "term", type: "uint256" },
    ],
    outputs: [{ type: "uint256" }],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "cancelListing",
    inputs: [{ name: "listingId", type: "uint256" }],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "updateListing",
    inputs: [
      { name: "listingId", type: "uint256" },
      { name: "newAmount", type: "uint256" },
      { name: "newApr", type: "uint256" },
      { name: "newTerm", type: "uint256" },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "submitOffer",
    inputs: [
      { name: "listingId", type: "uint256" },
      { name: "amount", type: "uint256" },
      { name: "apr", type: "uint256" },
      { name: "term", type: "uint256" },
    ],
    outputs: [],
    stateMutability: "payable",
  },
  {
    type: "function",
    name: "withdrawOffer",
    inputs: [{ name: "listingId", type: "uint256" }],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "acceptOffer",
    inputs: [
      { name: "listingId", type: "uint256" },
      { name: "lender", type: "address" },
      { name: "acceptedAmount", type: "uint256" },
      { name: "acceptedApr", type: "uint256" },
      { name: "acceptedTerm", type: "uint256" },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "repay",
    inputs: [{ name: "listingId", type: "uint256" }],
    outputs: [],
    stateMutability: "payable",
  },
  {
    type: "function",
    name: "repayPartial",
    inputs: [{ name: "listingId", type: "uint256" }],
    outputs: [],
    stateMutability: "payable",
  },
  {
    type: "function",
    name: "claimCollateral",
    inputs: [{ name: "listingId", type: "uint256" }],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "dispute",
    inputs: [{ name: "listingId", type: "uint256" }],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "resolve",
    inputs: [
      { name: "listingId", type: "uint256" },
      { name: "nftToLender", type: "bool" },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  // ── Read ──
  {
    type: "function",
    name: "listingCount",
    inputs: [],
    outputs: [{ type: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "listings",
    inputs: [{ name: "", type: "uint256" }],
    outputs: [
      { name: "borrower", type: "address" },
      { name: "nftContract", type: "address" },
      { name: "nftTokenId", type: "uint256" },
      { name: "principal", type: "uint256" },
      { name: "apr", type: "uint256" },
      { name: "term", type: "uint256" },
      { name: "acceptedLender", type: "address" },
      { name: "acceptedAmount", type: "uint256" },
      { name: "acceptedApr", type: "uint256" },
      { name: "acceptedTerm", type: "uint256" },
      { name: "fundedAt", type: "uint256" },
      { name: "repaidSoFar", type: "uint256" },
      { name: "stage", type: "uint8" },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "lenderDeposits",
    inputs: [
      { name: "", type: "uint256" },
      { name: "", type: "address" },
    ],
    outputs: [{ type: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "getRepaymentDue",
    inputs: [{ name: "listingId", type: "uint256" }],
    outputs: [
      { name: "totalDue", type: "uint256" },
      { name: "paid", type: "uint256" },
      { name: "remaining", type: "uint256" },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "getDeadline",
    inputs: [{ name: "listingId", type: "uint256" }],
    outputs: [{ type: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "getOfferCount",
    inputs: [{ name: "listingId", type: "uint256" }],
    outputs: [{ type: "uint256" }],
    stateMutability: "view",
  },
  // ── Mini Apps ──
  {
    type: "function",
    name: "listMiniApp",
    inputs: [
      { name: "price", type: "uint256" },
      { name: "metadataHash", type: "bytes32" },
    ],
    outputs: [{ type: "uint256" }],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "cancelMiniApp",
    inputs: [{ name: "listingId", type: "uint256" }],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "updateMiniApp",
    inputs: [
      { name: "listingId", type: "uint256" },
      { name: "newPrice", type: "uint256" },
      { name: "newMetadataHash", type: "bytes32" },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "verifyMiniApp",
    inputs: [{ name: "listingId", type: "uint256" }],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "miniAppCount",
    inputs: [],
    outputs: [{ type: "uint256" }],
    stateMutability: "view",
  },
  // ── Deal Escrow System ──
  {
    type: "function",
    name: "listDeal",
    inputs: [
      { name: "price", type: "uint256" },
      { name: "metadataHash", type: "bytes32" },
    ],
    outputs: [{ type: "uint256" }],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "cancelDeal",
    inputs: [{ name: "dealId", type: "uint256" }],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "updateDeal",
    inputs: [
      { name: "dealId", type: "uint256" },
      { name: "newPrice", type: "uint256" },
      { name: "newMetadataHash", type: "bytes32" },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "verifyDeal",
    inputs: [{ name: "dealId", type: "uint256" }],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "fundDeal",
    inputs: [{ name: "dealId", type: "uint256" }],
    outputs: [],
    stateMutability: "payable",
  },
  {
    type: "function",
    name: "markDelivered",
    inputs: [{ name: "dealId", type: "uint256" }],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "extendDeadline",
    inputs: [{ name: "dealId", type: "uint256" }],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "confirmDelivery",
    inputs: [{ name: "dealId", type: "uint256" }],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "disputeDeal",
    inputs: [{ name: "dealId", type: "uint256" }],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "resolveDeal",
    inputs: [
      { name: "dealId", type: "uint256" },
      { name: "buyerAmount", type: "uint256" },
      { name: "sellerAmount", type: "uint256" },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "refundDeal",
    inputs: [{ name: "dealId", type: "uint256" }],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "buyMiniApp",
    inputs: [{ name: "miniAppId", type: "uint256" }],
    outputs: [],
    stateMutability: "payable",
  },
  {
    type: "function",
    name: "deals",
    inputs: [{ name: "", type: "uint256" }],
    outputs: [
      { name: "seller", type: "address" },
      { name: "buyer", type: "address" },
      { name: "price", type: "uint256" },
      { name: "metadataHash", type: "bytes32" },
      { name: "deadline", type: "uint256" },
      { name: "createdAt", type: "uint256" },
      { name: "stage", type: "uint8" },
      { name: "buyerAmount", type: "uint256" },
      { name: "sellerAmount", type: "uint256" },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "dealCount",
    inputs: [],
    outputs: [{ type: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "dealEscrowBalance",
    inputs: [{ name: "", type: "uint256" }],
    outputs: [{ type: "uint256" }],
    stateMutability: "view",
  },
  // ── Pause ──
  {
    type: "function",
    name: "pause",
    inputs: [],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "unpause",
    inputs: [],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "paused",
    inputs: [],
    outputs: [{ type: "bool" }],
    stateMutability: "view",
  },
  // ── Offer tracking ──
  {
    type: "function",
    name: "offers",
    inputs: [
      { name: "", type: "uint256" },
      { name: "", type: "address" },
    ],
    outputs: [
      { name: "apr", type: "uint256" },
      { name: "term", type: "uint256" },
    ],
    stateMutability: "view",
  },
] as const;

export const ERC721_ABI = [
  {
    type: "function",
    name: "approve",
    inputs: [
      { name: "to", type: "address" },
      { name: "tokenId", type: "uint256" },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
] as const;
