[profile.default]
src = "contracts"
out = "out"
libs = ["lib"]
solc = "0.8.28"
evm_version = "cancun"
optimizer = true
optimizer_runs = 10
via_ir = true
verbosity = 3
remappings = [
    "forge-std/=lib/forge-std/src/",
]

[fuzz]
runs = 256

[rpc_endpoints]
base = "https://mainnet.base.org"

[invariant]
runs = 128
depth = 15
