import {
  defineToolcraftPerformance,
  type ToolcraftPerformanceConfig,
} from "@/toolcraft/runtime";

const customSmoothProfile = (target: string, value: unknown) => ({
  hardLimit: value,
  metric: "custom" as const,
  smoothTarget: value,
  smoothTargetRatio: 1,
  target,
  userFacingRange: "fully-guaranteed" as const,
});

const canvasSmoothProfile = (
  target: string,
  value: { height: number; width: number },
) => ({
  hardLimit: value,
  metric: "canvas-area" as const,
  smoothTarget: value,
  smoothTargetRatio: 1,
  target,
  userFacingRange: "fully-guaranteed" as const,
});

export const appPerformance: ToolcraftPerformanceConfig = defineToolcraftPerformance({
  browserCheckPolicy: {
    fallbackRunner: "playwright",
    fallbackWhen: ["agent-browser-unavailable", "ci"],
    preferredRunner: "agent-browser",
  },
  rendererPipeline: {
    interactionInvalidation: [
      {
        interaction: "control-change",
        invalidates: [
          "state-normalize",
          "dom-layout",
          "dom-composite",
          "export-composite",
        ],
        targets: [
          "prototype.screen",
          "prototype.modal",
          "prototype.device",
          "prototype.density",
          "prototype.role",
          "appearance.visualMode",
          "prototype.motion",
          "prototype.trustLevel",
          "appearance.accent",
          "export.includeBackground",
          "appearance.background",
          "export.image.format",
          "export.image.resolution",
        ],
      },
      {
        interaction: "control-drag",
        invalidates: ["dom-composite"],
        mustNotInvalidate: ["state-normalize", "dom-layout", "export-composite"],
        targets: ["motion.pulse"],
      },
      {
        interaction: "viewport-zoom",
        invalidates: ["dom-composite"],
        mustNotInvalidate: ["state-normalize", "dom-layout", "export-composite"],
        targets: ["canvas.viewport"],
      },
      {
        interaction: "export",
        invalidates: ["export-composite"],
        mustNotInvalidate: ["dom-layout"],
        targets: [
          "export.actions",
          "export.image.format",
          "export.image.resolution",
        ],
      },
    ],
    passes: [
      {
        cacheKey: [
          "prototype.screen",
          "prototype.modal",
          "prototype.device",
          "prototype.density",
          "prototype.role",
          "appearance.visualMode",
          "prototype.motion",
          "prototype.trustLevel",
          "appearance.accent",
          "export.includeBackground",
          "appearance.background",
          "motion.pulse",
        ],
        id: "state-normalize",
        inputs: [
          "prototype.screen",
          "prototype.modal",
          "prototype.device",
          "prototype.density",
          "prototype.role",
          "appearance.visualMode",
          "prototype.motion",
          "prototype.trustLevel",
          "appearance.accent",
          "export.includeBackground",
          "appearance.background",
          "motion.pulse",
        ],
        invalidatedBy: [
          "prototype.screen",
          "prototype.modal",
          "prototype.device",
          "prototype.density",
          "prototype.role",
          "prototype.motion",
          "prototype.trustLevel",
          "appearance.accent",
          "export.includeBackground",
          "appearance.background",
          "motion.pulse",
        ],
        kind: "preprocess",
        output: "intermediate",
        quality: "preview",
        runsOn: "main",
      },
      {
        cacheKey: [
          "state-normalize",
          "mock-data.catalog",
          "prototype.device",
          "prototype.density",
        ],
        id: "dom-layout",
        inputs: ["state-normalize", "mock-data.catalog"],
        invalidatedBy: [
          "prototype.screen",
          "prototype.modal",
          "prototype.device",
          "prototype.density",
          "prototype.role",
          "appearance.visualMode",
          "prototype.trustLevel",
        ],
        kind: "text-layout",
        output: "preview",
        quality: "full",
        runsOn: "main",
      },
      {
        cacheKey: [
          "dom-layout",
          "prototype.motion",
          "motion.pulse",
          "appearance.accent",
          "export.includeBackground",
          "appearance.background",
        ],
        id: "dom-composite",
        inputs: ["dom-layout", "motion.pulse", "appearance.accent"],
        invalidatedBy: [
          "prototype.motion",
          "motion.pulse",
          "appearance.accent",
          "export.includeBackground",
          "appearance.background",
        ],
        kind: "composite",
        output: "preview",
        quality: "full",
        runsOn: "main",
      },
      {
        cacheKey: [
          "state-normalize",
          "export.image.format",
          "export.image.resolution",
          "export.actions",
          "appearance.background",
          "export.includeBackground",
        ],
        id: "export-composite",
        inputs: [
          "state-normalize",
          "export.image.format",
          "export.image.resolution",
          "export.actions",
        ],
        invalidatedBy: [
          "export.image.format",
          "export.image.resolution",
          "export.actions",
          "appearance.background",
          "export.includeBackground",
        ],
        kind: "export",
        output: "export",
        quality: "export",
        runsOn: "export-only",
      },
    ],
  },
  rendererStrategy: "dom",
  rendererTechnique: {
    exportRenderer: "canvas-2d",
    fidelityRisks: [
      "PNG export is a summarized canvas rendering of the active prototype state rather than a pixel-perfect DOM screenshot.",
    ],
    layers: [
      {
        content: ["composite"],
        exportMode: "included",
        id: "backgroundLayer",
        kind: "background",
        primitiveCount: "low",
        renderer: "dom",
      },
      {
        content: ["geometry", "text"],
        exportMode: "included",
        id: "productForegroundLayer",
        kind: "product-foreground",
        primitiveCount: "medium",
        renderer: "dom",
        uiSelector: "[data-toolcraft-product-output]",
      },
      {
        content: ["composite", "geometry", "text"],
        exportMode: "composited",
        id: "exportComposite",
        kind: "export-composite",
        primitiveCount: "low",
        renderer: "canvas-2d",
      },
    ],
    performanceRisks: [
      "Full-page DOM switching and 8K export can be heavier than the default starter state.",
    ],
    previewExportDifferenceReason:
      "The live preview is an interactive DOM product mock; PNG export uses a simplified Canvas 2D composition with the same runtime state for portable review images.",
    previewRenderer: "dom",
    productRepresentation: "mixed",
    rendererStrategy: "dom",
    rendererWorkload: "simple-composition",
    sourceRepresentation: "procedural-data",
    whyNotAlternativeStrategies: [
      "text-output would lose the card, table, modal, icon, and rail hierarchy required for product-quality review.",
      "vector-output would make the responsive fintech interface harder to iterate than semantic DOM components.",
      "pixel-output would hide accessible text and controls behind a raster surface without improving this simple-composition workload.",
      "Canvas 2D is retained only for export/copy because it produces portable review images while the product-quality preview stays DOM.",
      "WebGL and WebGPU are unnecessary for soft cards, tables, modal workflows, and the animated escrow rail.",
    ],
  },
  rendererWorkload: "simple-composition",
  scenarios: [
    {
      automated: true,
      automatedTestName: "preview render stays under budget",
      browser: true,
      browserTestName: "browser perf: prototype preview render stays under budget",
      budget: { maxPreviewMs: 900 },
      expectedObservable:
        "The default full product preview is visible without blocking first interaction.",
      fixture: "default Baseshire home preview",
      id: "prototype-preview-render",
      interaction: "preview-render",
      workload: false,
    },
    {
      automated: true,
      automatedTestName: "screen switching stays responsive",
      browser: true,
      browserTestName: "browser perf: prototype screen switching stays responsive",
      budget: { maxFrameGapMs: 120, maxInteractionMs: 2000 },
      controlLabel: "Screen",
      expectedObservable:
        "Switching from Home to Market replaces the page content and keeps the shell responsive.",
      fixture: "market screen mock data",
      id: "prototype-screen-change",
      interaction: "control-change",
      target: "prototype.screen",
      workload: false,
    },
    {
      automated: true,
      automatedTestName: "modal workflow switching stays responsive",
      browser: true,
      browserTestName: "browser perf: prototype modal workflow stays responsive",
      budget: { maxFrameGapMs: 120, maxInteractionMs: 1500 },
      controlLabel: "Modal",
      expectedObservable:
        "Opening the connect wallet placeholder shows the workflow overlay without jank.",
      fixture: "wallet placeholder modal",
      id: "prototype-modal-change",
      interaction: "control-change",
      target: "prototype.modal",
      workload: false,
    },
    {
      automated: true,
      automatedTestName: "device preview switching stays responsive",
      browser: true,
      browserTestName: "browser perf: prototype device preview stays responsive",
      budget: { maxFrameGapMs: 120, maxInteractionMs: 900 },
      controlLabel: "Device",
      expectedObservable:
        "Switching device preview applies phone layout constraints without overlapping content.",
      fixture: "phone preview shell",
      id: "prototype-device-change",
      interaction: "control-change",
      target: "prototype.device",
      workload: false,
    },
    {
      automated: true,
      automatedTestName: "density switching stays responsive",
      browser: true,
      browserTestName: "browser perf: prototype density switching stays responsive",
      budget: { maxFrameGapMs: 120, maxInteractionMs: 900 },
      controlLabel: "Density",
      expectedObservable:
        "Compact density tightens the full page layout while keeping card content readable.",
      fixture: "compact market/admin density",
      id: "prototype-density-change",
      interaction: "control-change",
      stressFixture: {
        kind: "max-value",
        loadProfile: customSmoothProfile("prototype.density", "compact"),
        reason:
          "Compact density is the densest useful layout state for the prototype.",
        value: "compact",
      },
      target: "prototype.density",
      values: { default: "calm", max: "compact", min: "calm" },
      workload: true,
    },
    {
      automated: true,
      automatedTestName: "role switching stays responsive",
      browser: true,
      browserTestName: "browser perf: prototype role switching stays responsive",
      budget: { maxFrameGapMs: 120, maxInteractionMs: 900 },
      controlLabel: "Role",
      expectedObservable:
        "Switching to seller context updates trust copy and role-sensitive summaries.",
      fixture: "seller role fixture",
      id: "prototype-role-change",
      interaction: "control-change",
      target: "prototype.role",
      workload: false,
    },
    {
      automated: true,
      automatedTestName: "visual mode switching stays responsive",
      browser: true,
      browserTestName: "browser perf: prototype visual mode switching stays responsive",
      budget: { maxFrameGapMs: 120, maxInteractionMs: 1400 },
      controlLabel: "Visual mode",
      expectedObservable:
        "Switching visual mode changes terminal, editorial, or boardroom skin without remounting the whole product surface.",
      fixture: "editorial visual mode fixture",
      id: "appearance-visual-mode-change",
      interaction: "control-change",
      target: "appearance.visualMode",
      workload: false,
    },
    {
      automated: true,
      automatedTestName: "motion mode switching stays responsive",
      browser: true,
      browserTestName: "browser perf: prototype motion mode stays responsive",
      budget: { maxFrameGapMs: 120, maxInteractionMs: 1200 },
      controlLabel: "Motion",
      expectedObservable:
        "Switching to reduced motion disables decorative motion without hiding content.",
      fixture: "reduced motion fixture",
      id: "prototype-motion-change",
      interaction: "control-change",
      target: "prototype.motion",
      workload: false,
    },
    {
      automated: true,
      automatedTestName: "rail pulse dragging stays responsive",
      browser: true,
      browserTestName: "browser perf: rail pulse dragging stays responsive",
      budget: { maxFrameGapMs: 120, maxInteractionMs: 1500 },
      controlLabel: "Pulse",
      expectedObservable:
        "Dragging Pulse updates the animated escrow rail without shifting page layout.",
      fixture: "rail pulse control fixture",
      id: "motion-pulse-drag",
      interaction: "control-drag",
      target: "motion.pulse",
      workload: false,
    },
    {
      automated: true,
      automatedTestName: "trust mode switching stays responsive",
      browser: true,
      browserTestName: "browser perf: prototype trust mode stays responsive",
      budget: { maxFrameGapMs: 120, maxInteractionMs: 1600 },
      controlLabel: "Trust",
      expectedObservable:
        "Switching trust mode updates notices and status treatment without blocking.",
      fixture: "dispute trust fixture",
      id: "prototype-trust-change",
      interaction: "control-change",
      target: "prototype.trustLevel",
      workload: false,
    },
    {
      automated: true,
      automatedTestName: "accent editing stays responsive",
      browser: true,
      browserTestName: "browser perf: prototype accent editing stays responsive",
      budget: { maxFrameGapMs: 120, maxInteractionMs: 900 },
      controlLabel: "Royal blue",
      expectedObservable:
        "Editing the accent color updates brand mark, action, badge, and rail color.",
      fixture: "royal blue color edit fixture",
      id: "appearance-accent-change",
      interaction: "control-change",
      target: "appearance.accent",
      workload: false,
    },
    {
      automated: true,
      automatedTestName: "background editing stays responsive",
      browser: true,
      browserTestName: "browser perf: prototype background editing stays responsive",
      budget: { maxFrameGapMs: 120, maxInteractionMs: 900 },
      controlLabel: "background",
      expectedObservable:
        "Editing background updates the preview surface and export background color.",
      fixture: "background color edit fixture",
      id: "appearance-background-change",
      interaction: "control-change",
      target: "appearance.background",
      workload: false,
    },
    {
      automated: true,
      automatedTestName: "background include toggle stays responsive",
      browser: true,
      browserTestName: "browser perf: prototype background include stays responsive",
      budget: { maxFrameGapMs: 120, maxInteractionMs: 900 },
      controlLabel: "Include",
      expectedObservable:
        "Toggling Include changes preview background visibility without affecting content.",
      fixture: "transparent preview fixture",
      id: "export-include-background-change",
      interaction: "control-change",
      target: "export.includeBackground",
      workload: false,
    },
    {
      automated: true,
      automatedTestName: "image format switching stays responsive",
      browser: true,
      browserTestName: "browser perf: prototype image format switching stays responsive",
      budget: { maxFrameGapMs: 120, maxInteractionMs: 1400 },
      controlLabel: "Format",
      expectedObservable:
        "Changing image format updates the export file type control without blocking preview interaction.",
      fixture: "jpg export setting fixture",
      id: "export-image-format-change",
      interaction: "control-change",
      stressFixture: {
        kind: "max-value",
        loadProfile: customSmoothProfile("export.image.format", "jpg"),
        reason:
          "JPG is the alternate export format and exercises the same delivery path choice.",
        value: "jpg",
      },
      target: "export.image.format",
      values: { default: "png", max: "jpg", min: "png" },
      workload: true,
    },
    {
      automated: true,
      automatedTestName: "image resolution switching stays responsive",
      browser: true,
      browserTestName: "browser perf: prototype image resolution switching stays responsive",
      budget: { maxFrameGapMs: 120, maxInteractionMs: 1400 },
      controlLabel: "Resolution",
      expectedObservable:
        "Changing image resolution selects the heavy 8K export target without blocking the preview.",
      fixture: "8K export setting fixture",
      id: "export-image-resolution-change",
      interaction: "control-change",
      stressFixture: {
        kind: "large-canvas",
        loadProfile: canvasSmoothProfile("export.image.resolution", {
          height: 6144,
          width: 8192,
        }),
        reason:
          "8K is the largest selectable still export size for the design prototype.",
        value: { height: 6144, width: 8192 },
      },
      target: "export.image.resolution",
      values: { default: "4k", max: "8k", min: "2k" },
      workload: true,
    },
    {
      automated: true,
      automatedTestName: "png export completes within budget",
      browser: true,
      browserTestName: "browser perf: prototype png export completes within budget",
      budget: { maxExportMs: 4000 },
      expectedObservable:
        "Export PNG creates a downloadable image from the active prototype state.",
      fixture: "4K PNG export fixture",
      id: "prototype-png-export",
      interaction: "export-copy",
      stress: true,
      stressFixture: {
        kind: "large-canvas",
        loadProfile: canvasSmoothProfile("export.actions", {
          height: 3072,
          width: 4096,
        }),
        reason:
          "4K is the default shareable review export size and exercises the full export action.",
        value: { height: 3072, width: 4096 },
      },
      target: "export.actions",
      workload: false,
    },
    {
      automated: true,
      automatedTestName: "canvas viewport stays stable",
      browser: true,
      browserTestName: "browser perf: prototype canvas viewport stays stable",
      budget: { maxFrameGapMs: 120 },
      expectedObservable:
        "Changing page content does not jump the Toolcraft canvas viewport.",
      fixture: "canvas viewport stability fixture",
      id: "prototype-viewport-stability",
      interaction: "viewport-stability",
      workload: false,
    },
  ],
  usesCustomRenderer: true,
  workloadTargets: [
    "prototype.density",
    "export.image.format",
    "export.image.resolution",
  ],
});
